String longText = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eros nulla, pretium ut ornare eget, faucibus nec tellus. Donec dignissim cursus ornare. Etiam bibendum bibendum ullamcorper. Aliquam erat volutpat. Integer venenatis risus posuere, vulputate erat eget, rhoncus odio. Morbi quam nulla, varius vel nibh non, accumsan fermentum ligula. Nunc posuere turpis ac leo iaculis, ac efficitur mauris mollis. Duis tellus lacus, posuere consequat dapibus sed, laoreet sit amet arcu. Donec sagittis dui et turpis blandit finibus. In vitae efficitur tortor. In quis tincidunt libero. Pellentesque et vulputate lectus.

Proin pellentesque quis mi vitae ullamcorper. Cras eget risus metus. Etiam elementum enim nec arcu cursus, sit amet lobortis eros pharetra. Aenean et nulla ultricies, faucibus ante placerat, maximus nulla. Morbi non imperdiet dolor. Nulla eu mattis mi. Maecenas a rutrum orci. Aenean rutrum orci arcu, quis fermentum lectus euismod non. Fusce efficitur malesuada quam, in interdum velit convallis porta. Maecenas a ultrices ligula. Nunc sodales cursus lacus nec facilisis. Pellentesque eu sapien dolor. Nullam interdum mauris vitae lectus finibus, eget feugiat ligula ornare. Praesent sit amet lectus turpis. Aenean elit purus, commodo cursus feugiat ac, consectetur non risus. Praesent aliquam sed libero vitae bibendum.

Cras vitae gravida turpis. Donec sit amet massa ac est dignissim aliquam. Fusce rhoncus enim eu mi vulputate consectetur. Proin a dapibus magna, sit amet posuere odio. Ut efficitur, nulla et finibus ultrices, erat enim pharetra erat, maximus feugiat arcu mauris eget nisl. Donec in sapien diam. Sed id ultrices nisl, vitae ultricies magna. Mauris tempor hendrerit placerat. Praesent non eros ligula. Nullam sit amet egestas odio, et egestas mi. Donec scelerisque gravida eros in sodales. Nam nulla augue, blandit ac ante non, mattis congue elit. Fusce sodales tincidunt libero, sit amet posuere nisl faucibus at.

Nunc mollis lorem nibh, vel vehicula nunc consectetur nec. Quisque sagittis rutrum rutrum. Fusce vel hendrerit sem. Sed fringilla et orci tincidunt consequat. Phasellus ultricies, ipsum et sagittis rhoncus, odio nisi rutrum lorem, et mattis augue elit quis arcu. Ut et pretium enim. Curabitur efficitur libero in enim dictum sagittis. Aenean velit velit, rhoncus id leo vel, tristique sollicitudin mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Aliquam sed ipsum maximus, tempus sapien nec, mollis ex. Pellentesque aliquam placerat orci sed pharetra.

Sed venenatis augue vitae purus vulputate, in lacinia nibh lobortis. Integer diam sapien, porta ac cursus at, maximus at velit. Mauris maximus lacus quis magna sollicitudin congue ac sollicitudin turpis. Pellentesque quam lacus, placerat non fermentum vitae, porttitor quis libero. Morbi nibh lectus, blandit nec interdum nec, fermentum eu libero. Praesent eu magna vel turpis viverra gravida. Donec volutpat faucibus sodales.

Proin dapibus ac elit vitae consequat. Fusce dapibus ipsum augue, quis ultricies dui cursus quis. Suspendisse vel viverra felis. Aenean nulla tellus, auctor vitae felis quis, aliquam eleifend eros. Nullam vulputate pharetra metus in eleifend. Proin facilisis metus quis nunc posuere pulvinar id sed ligula. Integer at purus id justo laoreet pretium. Vestibulum fermentum nisi tortor, sit amet tempor urna hendrerit sit amet. Suspendisse vulputate lacus quis mi tincidunt dictum. Aenean sit amet ullamcorper nunc. Quisque lacus felis, cursus eleifend imperdiet vitae, lobortis id massa. Vestibulum est lectus, aliquet vitae sodales et, pulvinar at eros. Pellentesque nec erat bibendum, blandit mi ac, euismod lectus. Cras dui nibh, sollicitudin et arcu non, interdum porttitor eros. Suspendisse convallis aliquet lectus, sit amet vehicula est suscipit eu. Sed sit amet nisl eget massa consectetur mattis.

Sed suscipit ligula eget tempus consequat. Maecenas dapibus sed urna vel dictum. Maecenas mattis ut sapien id imperdiet. Proin fringilla posuere felis, nec mollis magna viverra id. Donec tempus vitae orci sit amet finibus. Praesent quis tristique mi, vitae viverra turpis. Phasellus et nibh varius, sagittis eros in, pellentesque nisi. Proin non ipsum accumsan, tincidunt mauris nec, scelerisque nisi.

Maecenas ut imperdiet lacus. Quisque ac quam dui. Nam lorem est, dignissim et diam eget, vehicula gravida sem. Suspendisse potenti. Aenean lobortis, felis quis condimentum congue, felis mi euismod nisl, nec pretium dolor elit et enim. Maecenas posuere risus risus, eget viverra tortor hendrerit vitae. Fusce tincidunt ex vitae ante faucibus ultricies.

Phasellus in odio et eros molestie interdum. Sed efficitur lorem metus, ac vehicula turpis rutrum eu. Vestibulum sit amet facilisis sem, nec sagittis dolor. Donec sed diam dui. Vivamus congue ante sem, sit amet molestie lacus facilisis vitae. Nullam risus quam, suscipit quis dignissim sit amet, convallis vel libero. Etiam auctor faucibus nunc sed viverra. Pellentesque et lacinia nisl, nec semper orci. Vestibulum et arcu libero. Mauris interdum ante vel turpis imperdiet lobortis. Pellentesque ut vestibulum dolor, sit amet iaculis mauris. Integer a laoreet lectus. Donec vestibulum orci quis porttitor consequat. Nam rhoncus urna vitae rutrum fermentum. Cras congue posuere felis quis porttitor. Ut felis odio, efficitur ut dolor vitae, sagittis feugiat sapien.

Nunc tincidunt molestie ligula eget rhoncus. Aliquam sagittis nunc dolor, et imperdiet quam ultricies faucibus. Donec dictum ut mi nec finibus. Pellentesque at blandit massa, a fringilla lacus. Donec id velit rutrum, aliquam quam non, venenatis nibh. Quisque mattis vulputate tortor at ornare. Integer dapibus suscipit ultrices. Nulla a ex ac quam dictum placerat a in nibh. Morbi in consequat neque. Morbi vitae nunc ex. Suspendisse dictum nisi ut vestibulum molestie. Quisque consectetur imperdiet eros et blandit.

Phasellus quis quam vitae tellus tincidunt ullamcorper rutrum eu orci. Integer auctor sapien ac metus vulputate, id pretium urna bibendum. Nulla hendrerit magna sem. Sed vel ante vestibulum, sagittis urna quis, commodo purus. Etiam nec scelerisque libero, id efficitur magna. Pellentesque eget risus at dui malesuada pretium et quis nisi. Curabitur euismod felis at metus fermentum, sed efficitur ex suscipit. Nullam ultrices malesuada purus tincidunt convallis. Nulla lorem libero, feugiat a eleifend nec, tempor eu neque. Nulla in augue ligula. Aliquam aliquet congue leo, vel iaculis odio faucibus ut. In mollis aliquet sapien, vitae consectetur mauris semper vitae.

Maecenas sagittis auctor velit eu imperdiet. Curabitur tempus cursus quam, ullamcorper viverra felis porttitor quis. Nulla at ullamcorper leo. Sed eget fermentum tellus, eu facilisis orci. Nunc quis faucibus risus, ut tincidunt est. Mauris nec leo convallis, aliquam nunc id, vestibulum velit. Morbi elementum erat est, tincidunt blandit purus cursus quis. Phasellus ultricies, leo non vulputate lobortis, metus lacus pulvinar nunc, ac efficitur orci felis et justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae eros ac mi ultricies egestas non a ante. Proin euismod blandit sagittis. Ut aliquam consectetur metus. Etiam urna nisi, interdum vitae magna sit amet, fringilla venenatis arcu. Vestibulum fringilla et elit in ornare. Fusce gravida metus quis orci sagittis, at luctus dolor interdum.

Phasellus vel diam sit amet nulla laoreet dapibus id eget ipsum. Nam convallis finibus dolor, a vulputate risus egestas in. Mauris consequat hendrerit tincidunt. Suspendisse pharetra imperdiet est sit amet ornare. Sed ut lectus eget lacus ullamcorper gravida eget id tellus. Nunc accumsan sapien mauris, nec efficitur ipsum pulvinar in. Sed et mi non urna consequat finibus.

Sed id urna hendrerit, tincidunt purus vitae, dapibus velit. Nulla convallis lobortis velit nec consectetur. Etiam ut tortor diam. Maecenas tincidunt dolor ac sapien posuere iaculis. Sed blandit, lacus in viverra vulputate, urna sem eleifend magna, quis lobortis orci nisi a risus. Pellentesque sit amet massa non libero tincidunt ultricies. Sed et arcu et mauris aliquam lobortis in sit amet ante. Cras fringilla turpis nisi, eget tempus quam condimentum et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam posuere, nulla at volutpat placerat, dui erat vestibulum mi, in vehicula odio lorem faucibus neque. Quisque nec mauris est. Praesent vitae iaculis ipsum. In vel lacus ac quam commodo tristique.

Nulla vel dictum nunc. Integer in risus est. Phasellus id diam ac tellus sodales porttitor sed a nibh. Duis rutrum viverra felis in molestie. Nullam nulla sem, cursus at dapibus nec, blandit et mauris. In in consequat diam. Aenean et risus ligula. Donec nec dui hendrerit, interdum velit ut, suscipit lorem.

                
""";
